/**
 * PDF Export Service for Central Assistant Chat
 * Generates professional PDF documents with Zynaptrix branding
 */

import { jsPDF } from 'jspdf';

export interface ChatMessage {
  role: 'agent' | 'user';
  content: string;
  images?: string[];
  timestamp?: string;
  machineId?: string;
  context_source?: string;
}

export interface ExportOptions {
  sessionId: number;
  sessionTitle?: string;
  machineContext?: string;
  messages: ChatMessage[];
}

export interface PDFStyles {
  primaryColor: string;
  userBgColor: string;
  assistantBgColor: string;
  headerColor: string;
  textColor: string;
  watermarkOpacity: number;
}

const DEFAULT_STYLES: PDFStyles = {
  primaryColor: '#1976D2',
  userBgColor: '#E3F2FD',
  assistantBgColor: '#F5F5F5',
  headerColor: '#1976D2',
  textColor: '#333333',
  watermarkOpacity: 0.15,
};

/**
 * Convert hex color to RGB array
 */
function hexToRgb(hex: string): [number, number, number] {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result
    ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)]
    : [0, 0, 0];
}

/**
 * Convert image URL to base64 data URI
 */
async function imageToBase64(url: string): Promise<string> {
  try {
    const response = await fetch(url);
    const blob = await response.blob();
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch (error) {
    console.error('Failed to convert image to base64:', error);
    return ''; // Return empty string for failed images
  }
}

/**
 * Add watermark to each page
 */
function addWatermark(doc: jsPDF) {
  const pageCount = (doc as any).internal.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    
    // Add diagonal watermark text
    const rgb = hexToRgb(DEFAULT_STYLES.primaryColor);
    doc.saveGraphicsState();
    doc.setGState(doc.GState({ opacity: DEFAULT_STYLES.watermarkOpacity }));
    doc.setTextColor(rgb[0], rgb[1], rgb[2]);
    doc.setFontSize(50);
    doc.setFont('helvetica', 'bold');
    
    // Center and rotate
    const centerX = pageWidth / 2;
    const centerY = pageHeight / 2;
    doc.text('ZYNAPTRIX', centerX, centerY, {
      align: 'center',
      angle: 45,
    });
    
    doc.restoreGraphicsState();
  }
}

/**
 * Add header to the document
 */
async function addHeader(doc: jsPDF, options: ExportOptions): Promise<number> {
  // Title section
  doc.setFontSize(20);
  const headerRgb = hexToRgb(DEFAULT_STYLES.headerColor);
  doc.setTextColor(headerRgb[0], headerRgb[1], headerRgb[2]);
  doc.setFont('helvetica', 'bold');
  doc.text('Chat Session Export', 105, 20, { align: 'center' });
  
  // Session metadata
  doc.setFontSize(10);
  const textRgb = hexToRgb(DEFAULT_STYLES.textColor);
  doc.setTextColor(textRgb[0], textRgb[1], textRgb[2]);
  doc.setFont('helvetica', 'normal');
  
  const metadata = [
    `Session ID: ${options.sessionId}`,
    `Exported: ${new Date().toLocaleString()}`,
  ];
  
  if (options.sessionTitle) {
    metadata.unshift(`Title: ${options.sessionTitle}`);
  }
  
  if (options.machineContext) {
    metadata.push(`Machine Context: ${options.machineContext}`);
  }
  
  let yPos = 32;
  metadata.forEach((line) => {
    doc.text(line, 15, yPos);
    yPos += 5;
  });
  
  // Separator line
  const primaryRgb = hexToRgb(DEFAULT_STYLES.primaryColor);
  doc.setDrawColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
  doc.setLineWidth(0.5);
  doc.line(15, yPos + 2, 195, yPos + 2);
  
  return yPos + 8; // Return Y position for content start
}

/**
 * Add footer to each page
 */
function addFooters(doc: jsPDF) {
  const pageCount = (doc as any).internal.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    
    // Footer separator line
    doc.setDrawColor(204, 204, 204);
    doc.setLineWidth(0.3);
    doc.line(15, pageHeight - 15, pageWidth - 15, pageHeight - 15);
    
    // Footer text
    doc.setFontSize(8);
    doc.setTextColor(102, 102, 102);
    doc.setFont('helvetica', 'normal');
    doc.text(
      'Generated by Zynaptrix Industrial Copilot Platform',
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    
    // Page number
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - 15,
      pageHeight - 10,
      { align: 'right' }
    );
  }
}

/**
 * Format message content with word wrapping
 */
function formatMessageContent(
  doc: jsPDF,
  content: string,
  maxWidth: number
): string[] {
  const lines = doc.splitTextToSize(content, maxWidth) as string[];
  return lines;
}

/**
 * Add a message bubble to the PDF
 */
async function addMessage(
  doc: jsPDF,
  message: ChatMessage,
  yPos: number,
  styles: PDFStyles
): Promise<number> {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const bubbleWidth = 160;
  const padding = 5;
  
  // Check if we need a new page
  if (yPos > pageHeight - 60) {
    doc.addPage();
    yPos = 20;
  }
  
  // Determine message alignment and color
  const isUser = message.role === 'user';
  const bgColor = isUser ? styles.userBgColor : styles.assistantBgColor;
  const xPos = isUser ? pageWidth - margin - bubbleWidth : margin;
  
  // Add timestamp
  if (message.timestamp) {
    doc.setFontSize(8);
    doc.setTextColor(153, 153, 153);
    doc.setFont('helvetica', 'normal');
    const timeText = new Date(message.timestamp).toLocaleTimeString();
    doc.text(timeText, isUser ? pageWidth - margin - 2 : margin + 2, yPos, {
      align: isUser ? 'right' : 'left',
    });
    yPos += 5;
  }
  
  // Format message content
  doc.setFontSize(10);
  const textRgb = hexToRgb(styles.textColor);
  doc.setTextColor(textRgb[0], textRgb[1], textRgb[2]);
  doc.setFont('helvetica', 'normal');
  const lines = formatMessageContent(doc, message.content, bubbleWidth - 2 * padding);
  
  const textHeight = lines.length * 5;
  const bubbleHeight = textHeight + 2 * padding;
  
  // Draw message bubble background
  const bgRgb = hexToRgb(bgColor);
  doc.setFillColor(bgRgb[0], bgRgb[1], bgRgb[2]);
  doc.setDrawColor(221, 221, 221);
  doc.roundedRect(xPos, yPos, bubbleWidth, bubbleHeight, 2, 2, 'FD');
  
  // Add text
  let textYPos = yPos + padding + 4;
  lines.forEach((line) => {
    doc.text(line, xPos + padding, textYPos);
    textYPos += 5;
  });
  
  yPos += bubbleHeight + 3;
  
  // Add images if present
  if (message.images && message.images.length > 0) {
    for (const imageUrl of message.images) {
      // Check if we need a new page for image
      if (yPos > pageHeight - 80) {
        doc.addPage();
        yPos = 20;
      }
      
      try {
        const base64Image = await imageToBase64(imageUrl);
        if (base64Image) {
          const imgWidth = bubbleWidth - 10;
          const imgHeight = 60; // Fixed height, could be dynamic based on aspect ratio
          
          doc.addImage(
            base64Image,
            'JPEG',
            isUser ? pageWidth - margin - bubbleWidth + 5 : margin + 5,
            yPos,
            imgWidth,
            imgHeight
          );
          
          yPos += imgHeight + 5;
        }
      } catch (error) {
        console.error('Failed to add image:', error);
        // Add placeholder text for failed images
        doc.setFontSize(8);
        doc.setTextColor(153, 153, 153);
        doc.text('[Image unavailable]', xPos + padding, yPos);
        yPos += 10;
      }
    }
  }
  
  // Add context source if present
  if (message.context_source) {
    doc.setFontSize(7);
    doc.setTextColor(102, 102, 102);
    doc.setFont('helvetica', 'italic');
    doc.text(
      `Source: ${message.context_source}`,
      isUser ? pageWidth - margin - 2 : margin + 2,
      yPos,
      { align: isUser ? 'right' : 'left' }
    );
    yPos += 5;
  }
  
  yPos += 5; // Spacing between messages
  
  return yPos;
}

/**
 * Main export function to generate PDF
 */
export async function exportChatToPDF(
  options: ExportOptions,
  onProgress?: (progress: number) => void
): Promise<void> {
  try {
    // Initialize PDF document
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });
    
    if (onProgress) onProgress(10);
    
    // Add header
    let yPos = await addHeader(doc, options);
    
    if (onProgress) onProgress(20);
    
    // Add messages
    const totalMessages = options.messages.length;
    for (let i = 0; i < totalMessages; i++) {
      const message = options.messages[i];
      yPos = await addMessage(doc, message, yPos, DEFAULT_STYLES);
      
      // Update progress
      if (onProgress) {
        const progress = 20 + Math.floor((i / totalMessages) * 60);
        onProgress(progress);
      }
    }
    
    if (onProgress) onProgress(85);
    
    // Add watermark to all pages
    addWatermark(doc);
    
    if (onProgress) onProgress(95);
    
    // Add footers to all pages
    addFooters(doc);
    
    if (onProgress) onProgress(98);
    
    // Generate filename
    const timestamp = new Date().toISOString().split('T')[0];
    const filename = `Zynaptrix_Chat_Session_${options.sessionId}_${timestamp}.pdf`;
    
    // Save the PDF
    doc.save(filename);
    
    if (onProgress) onProgress(100);
  } catch (error) {
    console.error('Failed to generate PDF:', error);
    throw new Error('PDF generation failed. Please try again.');
  }
}

/**
 * Export current session from chat history
 */
export async function exportCurrentSession(
  sessionId: number,
  messages: ChatMessage[],
  sessionTitle?: string,
  machineContext?: string,
  onProgress?: (progress: number) => void
): Promise<void> {
  if (!messages || messages.length === 0) {
    throw new Error('No messages to export. Chat history is empty.');
  }
  
  const options: ExportOptions = {
    sessionId,
    sessionTitle,
    machineContext,
    messages,
  };
  
  await exportChatToPDF(options, onProgress);
}
